EPS = '_'
AXIOM = 'S'
ARROW = '->'


TERMINAL_PATTERN = '[a-z]'
NONTERMINAL_PATTERN = '[A-Z]'
WORD_PATTERN = '[A-Za-z]*'
NONEMPTY_WORD_PATTERN = '[A-Za-z]+'

RULE_PATTERN_TYPE_0 = f'\\s*{NONTERMINAL_PATTERN}{WORD_PATTERN}\\s*{ARROW}\\s*({EPS}|{NONEMPTY_WORD_PATTERN})\\s*'
RULE_PATTERN_TYPE_1 = f'\\s*{WORD_PATTERN}{NONTERMINAL_PATTERN}{WORD_PATTERN}\\s*{ARROW}\\s*{NONEMPTY_WORD_PATTERN}\\s*'
RULE_PATTERN_TYPE_2 = f'\\s*{NONTERMINAL_PATTERN}\\s*{ARROW}\\s*({EPS|NONEMPTY_WORD_PATTERN})\\s*'
RULE_PATTERN_TYPE_3L = f'\\s*{NONTERMINAL_PATTERN}\\s*{ARROW}\\s*({EPS}|{NONTERMINAL_PATTERN}*{TERMINAL_PATTERN}*)\\s*'
RULE_PATTERN_TYPE_3R = f'\\s*{NONTERMINAL_PATTERN}\\s*{ARROW}\\s*({EPS}|{TERMINAL_PATTERN}*{NONTERMINAL_PATTERN}*)\\s*'